Add a 32-bit gold binary and use it.
BUG=none
TEST=none
Review URL: https://chromiumcodereview.appspot.com/9508007

git-svn-id: http://src.chromium.org/svn/trunk/deps/third_party/gold@124239 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

diff --git a/ld b/ld
--- a/ld
+++ b/ld
@@ -5,15 +5,18 @@
 
 # Wrapper script named "ld" that either executes gold or the system linker.
 
-# The gold binary was built on 64-bit Ubuntu Lucid.  Don't run it on
-# non-64-bit machines.  Note that "uname -m" prints the kernel architecture,
-# while this binary will also fail on 64-bit kernels with 32-bit userlands.
+# The gold binaries are built on 64-bit Ubuntu Lucid and 32-bit Ubuntu Lucid,
+# for x86_64 and i686, respectively.
+# Note that we do not use "uname -m" because it prints the kernel architecture,
+# which can cause failures on 64-bit kernels with 32-bit userlands.
 
 base_dir=$(dirname "$0")
 machine=$(getconf LONG_BIT)
 if [ "$machine" = "64" ]; then
     exec $base_dir/gold64 "$@"
+elif [ "$machine" = "32" ]; then
+    exec $base_dir/gold32 "$@"
 else
-    # Fall back on the ld found in $PATH.
-    exec ld "$@"
+    echo Unknown architecture
+    exit 1
 fi
